group "CGConceptTest/LearnOpenGL"
    include "CGConceptTest/src/LearnOpenGL/glfwConf"
    include "CGConceptTest/src/LearnOpenGL/gladConf"
    include "CGConceptTest/src/LearnOpenGL/HelloTriangle"
    include "CGConceptTest/src/LearnOpenGL/HelloTriangleWithClass"
    include "CGConceptTest/src/LearnOpenGL/Shaders"
    include "CGConceptTest/src/LearnOpenGL/Texture"
    include "CGConceptTest/src/LearnOpenGL/Texture"
    include "CGConceptTest/src/LearnOpenGL/Texture_exercise1"
    include "CGConceptTest/src/LearnOpenGL/Texture_exercise2"
    include "CGConceptTest/src/LearnOpenGL/Texture_exercise3"
    include "CGConceptTest/src/LearnOpenGL/Texture_exercise4"
group ""

group "CGConceptTest/EigenExamples"
    include "CGConceptTest/src/UseEigen/HelloEigen"
    include "CGConceptTest/src/UseEigen/OperationEigen"
group ""

group "CGConceptTest/SDLExamples"
    include "src/UseSDL/HelloSDL/"
    include "src/UseSDL/OpenGLSDL/"
group ""

group "CGConceptTest/SFMLExamples"
    include "src/UseSFML/HelloSFML/"
group ""
